FROM node:{{ node_version }}

# User and Working Directory
RUN useradd -G root -m {{ container_user }}
<% if (subProject) { -%>
WORKDIR {{ container_project_dir }}/<%= subProject %>
<% } else { -%>
WORKDIR {{ container_project_dir }}
<% } -%>

# Copy Files
<% if (subProject) { -%>
ADD <%= subProject %>.tar.gz ./
ADD init-<%= subProject %>.sh ./init.sh
<% } else { -%>
ADD {{ project_name }}.tar.gz ./
ADD init.sh ./init.sh
<% } -%>
RUN chown app ./init.sh
RUN chmod 550 ./init.sh

# Environment Variables
ENV NODE_ENV production

# Configure the port app listening to.
ENV APP_PORT {{ app_container_port }}
EXPOSE {{ app_container_port }}

# Execution
USER app
CMD ./init.sh
