---
# Define playbooks to run every deployment.
- name: build source code at local
  include: playbooks/build.yml
  tags: [build]

- name: move builded code to the hosts
  include: playbooks/distribute.yml
  tags: [distribute]

- name: build images & run containers
  include: playbooks/run.yml
  tags: [run]
